### ISSUE TITLE
re-enable attobot

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/RigidBodyDynamics.jl#402]
Just FYI: I had to re-enable attobot on the repos that I moved to JuliaRobotics. You might want to do the same.

**Comment by tkoolen** [comment]
Thanks, done.

**Comment by rdeits** [comment]
Also, actually making a release caused attobot to error out because the URL changed: https://github.com/JuliaRobotics/LCMCore.jl/issues/33 . I'm making a manual PR to fix it, assuming that's the right thing to do: https://github.com/JuliaLang/METADATA.jl/pull/13765 

Anyway, I'll let you know what the procedure turns out to be.

**Comment by tkoolen** [comment]
You might want to do FemtoCleaner as well.

**Comment by rdeits** [comment]
Good point, thanks.
