### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/RigidBodyDynamics.jl#425]
It would be great to have the planar joint URDF parsing in a released version so I can depend on it in atlas-distro. Is this a good time for 0.5.1?

**Comment by tkoolen** [comment]
OK. It would be 0.6 according to semver though.

**Comment by tkoolen** [comment]
Are all your packages already working with RigidBodyDynamics master?

**Comment by rdeits** [comment]
Successfully tested: 

- [-] MechanismGeometries
- [-] MeshCatMechanisms
- [-] RigidBodyTreeInspector
- [-] LCPSim

**Comment by tkoolen** [comment]
Great, thank you!

To do:

* [ ] Run tests from previous released version against master. Ensure that there are reasonable deprecation messages, etc.
* [ ] Run tests for registered dependencies:
  * [x] MechanismGeometries
  * [x] MeshCatMechanisms
  * [x] RigidBodyTreeInspector
  * [ ] MotionCaptureJointCalibration
  * [ ] RigidBodySim
  * [ ] ValkyrieRobot
  * [ ] AtlasRobot
* Run tests for unregistered dependencies:
  * [x] LCPSim
  * [ ] HumanoidLCMSim
* [ ] Ensure that docs are up to date and that they build properly
* [ ] Update benchmark results, if relevant
* [ ] Use Attobot to set up release
* [ ] Update `NEWS.md`
