### ISSUE TITLE
Array conversions consistency

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/RigidBodyDynamics.jl#434]
To get a flat state vector from a `MechanismState`, we do `Vector(state)`, but to get a plain matrix from a GeometricJacobian, we do `Array(J)` not `Matrix(J)`. It would be nice to make those consistent. I'd suggest allowing `Matrix(J)` and possibly deprecating `Array(J)` in the future. This also comes up with `SpatialInertia`, `MomentumMatrix`, etc.

**Comment by tkoolen** [comment]
I guess Base allows `Array(A)`, `Matrix(A)`, and even `Array{Float64}(A)` and `Matrix{Float64}(A)`, so I'm not sure about deprecating `Array(J)`. But I agree this should be made more consistent.

**Comment by tkoolen** [comment]
Using SparseArrays as an example, this all works:

```julia
using SparseArrays
x = spzeros(Float32, 4)
Vector(x)
Vector{Float64}(x
Array(x)
Array{Float64}(x)
```
