### ISSUE TITLE
Last release to support 0.6

### ISSUE THREAD

**Issue by tkoolen** [JuliaRobotics/RigidBodyDynamics.jl#446]
To do:

* [x] check REQUIRE files
* [x] remove deprecations from last version
* [x] Run tests from previous released version against master. Ensure that there are reasonable deprecation messages, etc.
* Run tests for registered dependencies:
  * [x] MechanismGeometries
  * [x] MeshCatMechanisms
  * [x] RigidBodyTreeInspector
  * [x] MotionCaptureJointCalibration
  * [x] RigidBodySim
  * [x] ValkyrieRobot
  * [x] AtlasRobot
* Run tests for unregistered dependencies:
  * [ ] LCPSim
  * [x] HumanoidLCMSim
* [x] Ensure that docs are up to date and that they build properly
* [x] Update benchmark results, if relevant
* [x] Use Attobot to set up release
* [x] Update `NEWS.md`

**Comment by tkoolen** [comment]
Release notes:

* Compatibility with Julia 0.7-beta (save for some notebooks due to additional test dependencies), with some deprecation warnings
* Store motion subspaces and wrench subspaces column by column in `MechanismState`. This allows dropping two type parameters from `MechanismState` (`MotionSubspaceCollection` and `WrenchSubspaceCollection`). See https://github.com/JuliaRobotics/RigidBodyDynamics.jl/pull/435 for more info.
* Add `point_jacobian!`/`point_jacobian` (thanks, @rdeits!)
* Implement Jacobians for q̇ <-> v (thanks, @rdeits!)

**Comment by rdeits** [comment]
No problem. That package is still in research-code-land and I'm only bothering to keep it working with RBD master.

**Comment by tkoolen** [comment]
But this was with latest master? Anyway, https://github.com/JuliaLang/METADATA.jl/pull/15493.

**Comment by rdeits** [comment]
Oh, I see what's going on. It's calling the in-place per-joint method, but we got rid of that method during the updates to #440 when we switched them to return static arrays instead. Anyway, i'll make sure it works with master again.
