### ISSUE TITLE
Is it possible to detect crashes with RigidBodyDynamics.jl?

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaRobotics/RigidBodyDynamics.jl#546]
Hi. Is crash detection now available for RigidBodyDynamics.jl? I am working with `Box2D` in python, and I was looking at this package as a possible substitute.

**Comment by tkoolen** [comment]
What is your definition of a crash?

**Comment by kraftpunk97** [comment]
@tkoolen Sorry if I'm unable to get my point across; I'm still trying to figure out what needs to be done. I am working on bringing the Lunar Lander arcade game to Julia which is written using the Box2D library. While searching for Julian alternatives for the library, I found RigidBodyDynamics.jl. But [your comment in this issue](https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/110#issuecomment-257652238) says that "contact", (Sorry, I meant to say "contact" instead of "crash" in my original post) is not yet implemented. But that issue is from 2016, and I was wondering if this feature has been implemented. I had a quick glance over the docs, but I didn't find anything about it or I must have missed it in my hurry. Again, I apologise for being unclear.

**Comment by kraftpunk97** [comment]
pinging @tkoolen

**Comment by tkoolen** [comment]
Contact is currently limited to body-fixed contact points interacting with an environment consisting of halfspaces. Unfortunately I haven't had the time / personal need to focus on this beyond the current capabilities for a while now. I may need more complex geometry at some point in the coming months for my own work, but that's the status quo.
