### ISSUE TITLE
some puzzle at spatial acceleration transition

### ISSUE THREAD

**Issue by kuro26** [JuliaRobotics/RigidBodyDynamics.jl#597]
The realization of spatial acceleration transition is quite different from described in book. 
![image](https://user-images.githubusercontent.com/24366723/104282127-875c0500-54e9-11eb-9f84-e2edf0771922.png)
The book tells that $v_A$ is the spatial velocity of target frame wrt. old frame, The realized code maybe give a frame A' the same spatial velocity with A, and first transit to A' then to A. I mean , the second parameter maybe twist_of_new_wrt_current instead of twist_of_current_wrt_new, I'm not sure if I am right.

**Comment by tkoolen** [comment]
Basically, the `transform(accel::SpatialAcceleration, old_to_new::Transform3D, twist_of_current_wrt_new::Twist, twist_of_body_wrt_base::Twist)` method implements the derivative of `function transform(twist::Twist, tf::Transform3D)` without making any assumptions on `twist` and `tf` other than that the frames make sense. The math for this is as follows (from a personal technical document, using different notation from Duindam's thesis):

<img width="504" alt="image" src="https://user-images.githubusercontent.com/2585880/106542363-b30f5100-64d1-11eb-8b0d-6f43353b8ceb.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2585880/106542438-d803c400-64d1-11eb-90e7-89a7f6657464.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2585880/106542508-f7025600-64d1-11eb-8c71-1998da2db941.png">

So the `transform` method for spatial accelerations is a generalization of the (2.36) in Featherstone's book, in that it doesn't assume that $H^m_i$ is the identity.
