### ISSUE TITLE
PR2 submechanism for one arm only

### ISSUE THREAD

**Issue by dhruvms** [JuliaRobotics/RigidBodyDynamics.jl#619]
The [PR2 URDF](https://gist.github.com/dhruvms/513484f143f949c99c77f05551b2ba49) that I am using has a 45-dimensional joint configuration vector. For my application, I only care about 7 of those joints in the right arm. The first of those (_r_shoulder_pan_joint_) joins _torso_lift_link_ and _r_shoulder_pan_link_, but _torso_lift_link_ has three other child branches that I do not care about. I have tried:
1. Using `submechanism`
    - Rooting it at _torso_lift_link_ brings the three child branches that I do not care about into the mechanism.
    - Rooting it at _r_shoulder_pan_link_ means I lose _r_shoulder_pan_joint_ in my mechanism.
2. Using `remove_joint!`
    - For this URDF at least, any call that I have tried to make to `remove_joint!` gives me a _"Graph is not connected."_ error.

Is there a way to work with a partial chain from a URDF?

**Comment by tkoolen** [comment]
You should be able to use the `remove_subtree!` function I just added to do this. Let me know if there's any trouble.
