### ISSUE TITLE
Is the demo of `4. Jacobian IK and Control` correct?

### ISSUE THREAD

**Issue by wly2014** [JuliaRobotics/RigidBodyDynamics.jl#631]
In the function `jacobian_transpose_ik!` of demo in 4. [Jacobian IK and Control](https://juliarobotics.org/RigidBodyDynamics.jl/stable/generated/4.%20Jacobian%20IK%20and%20Control/4.%20Jacobian%20IK%20and%20Control/), the transpose of `Array(Jp)` is used to calculate the `Δq`. But the inverse or pseudo-inverse of Jacobian should be used referring to others, such as [this](https://robotics.stackexchange.com/a/522).

**Comment by rdeits** [comment]
Jacobian-transpose and Jacobian-pseudo-inverse are both correct approaches (with some trade-offs in convergence rate, stability, and computational cost). For a more detailed overview of both, check out http://graphics.cs.cmu.edu/nsp/course/15-464/Spring11/handouts/iksurvey.pdf
